package common.enums;

public enum ResponseCodeEnum {
	OK,
	INTERNAL_SERVER_ERROR,
	INVALID_USERNAME_PASSWORD,
	INVALID_USERNAME,
	INVALID_COMMAND,
	BAD_REQUEST,
	USERNAME_ALREADY_USED,
	USERNAME_REQUIRED,
	PASSWORD_REQUIRED,
	INVALID_WORD_LENGHT,
	WORD_NOT_IN_DICTIONARY,
	GAME_WON,
	GAME_LOST,
	GAME_ALREADY_PLAYED,
	NEED_TO_START_GAME,
	NO_GAME_TO_SHARE,
	ALREADY_LOGGED_IN;
}
