package common.enums;

public enum ResponseCodeEnum {
	INVALID_USERNAME_PASSWORD,
	USERNAME_ALREADY_USED,
	USERNAME_REQUIRED,
	PASSWORD_REQUIRED,
	INVALID_WORD_LENGHT,
	WORD_NOT_IN_DICTIONARY,
	GAME_WON,
	GAME_LOST,
	GAME_ALREADY_PLAYED;
}
